export const REASON_CODES = {
  INTENT_EXPIRED: 'INTENT_EXPIRED',
  CHAIN_OUT_OF_SCOPE: 'CHAIN_OUT_OF_SCOPE',
  TARGET_NOT_ALLOWED: 'TARGET_NOT_ALLOWED',
  SELECTOR_NOT_ALLOWED: 'SELECTOR_NOT_ALLOWED',
  RECIPIENT_NOT_ALLOWED: 'RECIPIENT_NOT_ALLOWED',
  ASSET_NOT_BUDGETED: 'ASSET_NOT_BUDGETED',
  GROSS_OUTFLOW_EXCEEDED: 'GROSS_OUTFLOW_EXCEEDED',
  ALLOWANCE_EXPOSURE_EXCEEDED: 'ALLOWANCE_EXPOSURE_EXCEEDED',
  GAS_BUDGET_EXCEEDED: 'GAS_BUDGET_EXCEEDED',
  SLIPPAGE_EXCEEDED: 'SLIPPAGE_EXCEEDED',
  DEADLINE_EXCEEDED: 'DEADLINE_EXCEEDED',
  DEBT_CAP_EXCEEDED: 'DEBT_CAP_EXCEEDED',
  FINAL_GOAL_UNSATISFIED: 'FINAL_GOAL_UNSATISFIED',
  UNKNOWN_EFFECT: 'UNKNOWN_EFFECT',
  PARTIAL_DECODE: 'PARTIAL_DECODE',
  SIMULATION_FAILED: 'SIMULATION_FAILED',
  MISSING_QUOTE: 'MISSING_QUOTE',
  FINAL_STATE_UNAVAILABLE: 'FINAL_STATE_UNAVAILABLE',
} as const;

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];
